# Generated by Django 6.1 on 2026-08-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='client_phone_secondary',
            field=models.CharField(blank=True, help_text='Secondary Client Phone', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='quotation_title',
            field=models.CharField(default='Labour Quotation', max_length=200),
        ),
        migrations.AlterField(
            model_name='bill',
            name='architect_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='bill',
            name='client_phone',
            field=models.CharField(help_text='Primary Client Phone', max_length=20),
        ),
    ]
