# Generated by Django 6.0 on 2026-08-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_bill_client_phone_secondary_bill_quotation_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Optional description or materials used'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture_url',
            field=models.TextField(blank=True, help_text='External image URL fallback'),
        ),
    ]
